/**
 * Feature 013 T056 — the exact PRE-M3 failing baseline, recorded live on 2026-09-26 against production
 * (M1–M2e applied, M3 NOT applied, bank_transfer_checkout_enabled = false).
 *
 * Each entry is a case whose DESIRED post-M3 outcome (contracts/rls-storage.md §1/§2, tasks.md T056/T057) does not hold
 * today. In the default PRE_M3 phase the suites require every listed case to still FAIL and every other case to PASS,
 * so any drift is caught in both directions. T062 runs the same suites with F013_RLS_PHASE=POST_M3, which requires every
 * case, including these, to PASS. Do not edit these lists except together with the M3 review.
 *
 * Amended 2026-09-26 by the T060 owner decision F1 (six expectations, nothing else): the BUYER × orders destination-column
 * cell now requires "permission denied" (R1 column boundary) and is therefore a PRE-M3 failure; the five ANON × §2-view
 * "(fixture rows)" cells now require "permission denied" (they were and remain PRE-M3 failures: the views do not exist yet).
 */

/** rls-seller-isolation.live.test.ts — 28 cases (SELLER_1 / SELLER_2 of the two-seller fixture order). */
export const T056_PRE_M3_SELLER_FAILURES: readonly string[] = [
  "orders.delivery_destination_id/destination_snapshot (R1) × SELLER_1",
  "orders.delivery_destination_id/destination_snapshot (R1) × SELLER_2",
  "order_items × SELLER_1",
  "order_items × SELLER_2",
  "order_financials × SELLER_1",
  "order_financials × SELLER_2",
  "proforma_invoices × SELLER_1",
  "proforma_invoices × SELLER_2",
  "proforma_invoice_items × SELLER_1",
  "proforma_invoice_items × SELLER_2",
  "proforma_line_economics × SELLER_1",
  "proforma_line_economics × SELLER_2",
  "proforma_fulfillment_groups × SELLER_1",
  "proforma_fulfillment_groups × SELLER_2",
  "proforma_seller_settlements × SELLER_1",
  "proforma_seller_settlements × SELLER_2",
  "payments × SELLER_1",
  "payments × SELLER_2",
  "payment_proofs × SELLER_1",
  "payment_proofs × SELLER_2",
  "tax_invoices × SELLER_1",
  "tax_invoices × SELLER_2",
  "order_shipments (FULFILLMENT) × SELLER_1",
  "order_shipments (FULFILLMENT) × SELLER_2",
  "v_seller_order_lines (access) × SELLER_1",
  "v_seller_order_lines (access) × SELLER_2",
  "orders destination via embedded order_items→orders select (R1) × SELLER_1",
  "orders destination via embedded order_items→orders select (R1) × SELLER_2",
];

/** rls-role-matrix.live.test.ts — 82 cases (buyer / other buyer / seller 1 / seller 2 / finance / warehouse / auditor / anon). */
export const T056_PRE_M3_MATRIX_FAILURES: readonly string[] = [
  "orders.delivery_destination_id/destination_snapshot (R1) × BUYER",
  "orders.delivery_destination_id/destination_snapshot (R1) × SELLER_1",
  "orders.delivery_destination_id/destination_snapshot (R1) × SELLER_2",
  "order_items × SELLER_1",
  "order_items × SELLER_2",
  "order_items × FINANCE",
  "order_financials × SELLER_1",
  "order_financials × SELLER_2",
  "proforma_invoices × SELLER_1",
  "proforma_invoices × SELLER_2",
  "proforma_invoices × FINANCE",
  "proforma_invoice_items × SELLER_1",
  "proforma_invoice_items × SELLER_2",
  "proforma_invoice_items × FINANCE",
  "proforma_line_economics × SELLER_1",
  "proforma_line_economics × SELLER_2",
  "proforma_line_economics × FINANCE",
  "proforma_fulfillment_groups × BUYER",
  "proforma_fulfillment_groups × SELLER_1",
  "proforma_fulfillment_groups × SELLER_2",
  "proforma_fulfillment_groups × FINANCE",
  "proforma_fulfillment_groups × WAREHOUSE",
  "proforma_seller_settlements × SELLER_1",
  "proforma_seller_settlements × SELLER_2",
  "proforma_seller_settlements × FINANCE",
  "proforma_bank_instructions × BUYER",
  "proforma_bank_instructions × FINANCE",
  "payments × SELLER_1",
  "payments × SELLER_2",
  "payments × AUDITOR",
  "payment_proofs × SELLER_1",
  "payment_proofs × SELLER_2",
  "payment_proofs × AUDITOR",
  "reconciliation_cases × FINANCE",
  "reconciliation_case_events × FINANCE",
  "manual_financial_adjustments × FINANCE",
  "manual_financial_adjustments × AUDITOR",
  "tax_invoices × SELLER_1",
  "tax_invoices × SELLER_2",
  "order_shipments (FULFILLMENT) × SELLER_1",
  "order_shipments (FULFILLMENT) × SELLER_2",
  "order_shipments (FULFILLMENT) × FINANCE",
  "v_audit_payments (access) × AUDITOR",
  "v_audit_payments (fixture rows) × BUYER",
  "v_audit_payments (fixture rows) × OTHER_BUYER",
  "v_audit_payments (fixture rows) × SELLER_1",
  "v_audit_payments (fixture rows) × SELLER_2",
  "v_audit_payments (fixture rows) × FINANCE",
  "v_audit_payments (fixture rows) × WAREHOUSE",
  "v_audit_payments (fixture rows) × ANON",
  "v_audit_proformas (access) × AUDITOR",
  "v_audit_proformas (fixture rows) × BUYER",
  "v_audit_proformas (fixture rows) × OTHER_BUYER",
  "v_audit_proformas (fixture rows) × SELLER_1",
  "v_audit_proformas (fixture rows) × SELLER_2",
  "v_audit_proformas (fixture rows) × FINANCE",
  "v_audit_proformas (fixture rows) × WAREHOUSE",
  "v_audit_proformas (fixture rows) × ANON",
  "v_buyer_reconciliation (access) × BUYER",
  "v_buyer_reconciliation (fixture rows) × OTHER_BUYER",
  "v_buyer_reconciliation (fixture rows) × SELLER_1",
  "v_buyer_reconciliation (fixture rows) × SELLER_2",
  "v_buyer_reconciliation (fixture rows) × FINANCE",
  "v_buyer_reconciliation (fixture rows) × WAREHOUSE",
  "v_buyer_reconciliation (fixture rows) × AUDITOR",
  "v_buyer_reconciliation (fixture rows) × ANON",
  "v_finance_review_queue (access) × FINANCE",
  "v_finance_review_queue (fixture rows) × BUYER",
  "v_finance_review_queue (fixture rows) × OTHER_BUYER",
  "v_finance_review_queue (fixture rows) × SELLER_1",
  "v_finance_review_queue (fixture rows) × SELLER_2",
  "v_finance_review_queue (fixture rows) × WAREHOUSE",
  "v_finance_review_queue (fixture rows) × AUDITOR",
  "v_finance_review_queue (fixture rows) × ANON",
  "v_seller_order_lines (access) × SELLER_1",
  "v_seller_order_lines (access) × SELLER_2",
  "v_seller_order_lines (fixture rows) × BUYER",
  "v_seller_order_lines (fixture rows) × OTHER_BUYER",
  "v_seller_order_lines (fixture rows) × FINANCE",
  "v_seller_order_lines (fixture rows) × WAREHOUSE",
  "v_seller_order_lines (fixture rows) × AUDITOR",
  "v_seller_order_lines (fixture rows) × ANON",
];

/** rls-anon-probe.live.test.ts — DB-OPEN-C15 (in-database role probes + the real anonymous REST path). */
export const T056_PRE_M3_ANON_FAILURES: readonly string[] = [
  "C15: anon cannot EXECUTE mfa_satisfied()",
  "C15: anon cannot EXECUTE kyb_storage_object_authorized(text, boolean)",
  "C15 ACL: anon holds no EXECUTE on mfa_satisfied()",
  "C15 ACL: anon holds no EXECUTE on kyb_storage_object_authorized(text, boolean)",
  "C15 REST: anon POST rpc/mfa_satisfied is refused",
  "C15 REST: anon POST rpc/kyb_storage_object_authorized is refused",
];
