import type { Metadata } from "next";
import { Cairo, Readex_Pro } from "next/font/google";
import localFont from "next/font/local";

import { LocaleProvider } from "@/components/locale/locale-provider";
import { preferenceScript } from "@/components/theme/preferences";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { I18nProvider } from "@/lib/i18n/config";
import "./globals.css";

const benito = localFont({
  variable: "--font-benito",
  display: "swap",
  src: [
    { path: "../../public/fonts/Benito-Thin.ttf", weight: "100" },
    { path: "../../public/fonts/Benito-Light.ttf", weight: "300" },
    { path: "../../public/fonts/Benito-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/Benito-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/Benito-Bold.ttf", weight: "700" },
    { path: "../../public/fonts/Benito-Black.ttf", weight: "900" },
  ],
});

const manrope = localFont({
  variable: "--font-manrope",
  display: "swap",
  src: [
    { path: "../../public/fonts/Manrope-ExtraLight.ttf", weight: "200" },
    { path: "../../public/fonts/Manrope-Light.ttf", weight: "300" },
    { path: "../../public/fonts/Manrope-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/Manrope-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/Manrope-SemiBold.ttf", weight: "600" },
    { path: "../../public/fonts/Manrope-Bold.ttf", weight: "700" },
    { path: "../../public/fonts/Manrope-ExtraBold.ttf", weight: "800" },
  ],
});

const readexPro = Readex_Pro({
  variable: "--font-readex-pro",
  subsets: ["arabic", "latin"],
  display: "swap",
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    /*
     * `suppressHydrationWarning` is required and deliberate (Phase 5.5, UIF-016/UIF-017).
     *
     * The blocking script below writes `class`, `lang`, `dir` and `color-scheme` onto this element
     * BEFORE the body paints — that is what removes the flash of wrong theme and wrong direction.
     * React also owns `<html>`, so without this attribute it would report those script-applied values
     * as a hydration mismatch.
     *
     * This is React's sanctioned escape hatch for exactly this case (server-injected attributes on
     * `html`/`body`), and it is scoped to this element only: it suppresses nothing inside `<body>`,
     * so a genuine mismatch anywhere in the application still surfaces normally.
     */
    <html
      lang="en"
      dir="ltr"
      suppressHydrationWarning
      className={`${benito.variable} ${manrope.variable} ${readexPro.variable} ${cairo.variable} h-full antialiased`}
    >
      <head>
        {/*
          Applied before first paint, ahead of any bundle. Inline and blocking on purpose: a
          preference read after hydration would paint the wrong theme and the wrong direction first,
          then visibly correct itself. The script only touches `documentElement` — it sets no cookie
          and makes no request, so no public route becomes dynamic and the Feature-001 cache
          architecture is untouched (Constitution XI).
        */}
        <script dangerouslySetInnerHTML={{ __html: preferenceScript() }} />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <LocaleProvider>
            <I18nProvider>{children}</I18nProvider>
          </LocaleProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
